[project]
title = "Stock Portfolio Dashboard by Bryan Yoo"
version = "0.1.0"
port = 8501
slug = "my-project-266451"  
entrypoint = "hello.py"    

[branding]
name = "Stock Portfolio"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#5b8064"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[data.portfolio_csv]
type = "csv"
path = "data/portfolio.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"